services:
  - type: web
    name: motimate-app
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
